---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Install Package
      yum:
        name: "{{ apache_package }}"
        state: present
        
    - name: Start Apache
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes


